"""Pack NYC's parks and other green spaces into a small file for the map.

Usage (needs pyarrow):
    python3 scripts/build_parks.py nyc_land_use.parquet src/data/nycBoroughs.json src/data/nycParks.js

Input: Overture Maps land-use areas for NYC (built from OpenStreetMap),
downloaded with scripts/fetch_overture.py. We keep parks, golf courses,
cemeteries, nature reserves and recreation grounds: the green areas Google
Maps shows. (We skip "garden" and "grass", which in this data are mostly
backyards and road medians.) Shapes are simplified and packed the same way
as the streets in build_roads.py.
"""

import base64
import json
import math
import struct
import sys

import pyarrow.parquet as pq

from build_roads import ORIGIN, SCALE, borough_mask, in_nyc, simplify, varint

GREEN = {
    ("park", "park"), ("park", "village_green"), ("park", "dog_park"),
    ("golf", "golf_course"), ("cemetery", "cemetery"), ("cemetery", "grave_yard"),
    ("protected", "nature_reserve"), ("recreation", "recreation_ground"),
}
TOLERANCE = 0.00003  # degrees, about 3 m
MIN_AREA = 200  # m²; smaller patches are invisible even zoomed in
LARGE, MEDIUM = 200_000, 20_000  # m²; decides the zoom a park first appears at


def parse_wkb_polygons(wkb):
    """Return a list of polygons, each a list of rings [(lng, lat), ...]."""
    def read_polygon(off):
        order = "<" if wkb[off] == 1 else ">"
        (count,) = struct.unpack_from(order + "I", wkb, off + 5)
        off += 9
        rings = []
        for _ in range(count):
            (n,) = struct.unpack_from(order + "I", wkb, off)
            pts = struct.unpack_from(order + "d" * (2 * n), wkb, off + 4)
            rings.append(list(zip(pts[0::2], pts[1::2])))
            off += 4 + 16 * n
        return rings, off

    order = "<" if wkb[0] == 1 else ">"
    (gtype,) = struct.unpack_from(order + "I", wkb, 1)
    gtype %= 1000
    if gtype == 3:
        return [read_polygon(0)[0]]
    if gtype == 6:
        (count,) = struct.unpack_from(order + "I", wkb, 5)
        off, polys = 9, []
        for _ in range(count):
            rings, off = read_polygon(off)
            polys.append(rings)
        return polys
    return []


def area_m2(ring):
    lat = math.radians(ring[0][1])
    kx, ky = 111_320 * math.cos(lat), 110_540
    return abs(sum(x1 * kx * y2 * ky - x2 * kx * y1 * ky for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1]))) / 2


def main(src, boroughs, dst):
    mask = borough_mask(boroughs)
    rows = pq.read_table(src, columns=["subtype", "class", "geometry"]).to_pylist()
    out = bytearray()
    parks = points = 0
    sizes = [0, 0, 0]
    for row in rows:
        if (row["subtype"], row["class"]) not in GREEN:
            continue
        for rings in parse_wkb_polygons(row["geometry"]):
            outer = rings[0]
            area = area_m2(outer)
            if area < MIN_AREA or not in_nyc(outer, mask):
                continue
            packed = []
            for ring in rings:
                ring = simplify(ring, TOLERANCE)
                q = [(round((x - ORIGIN[0]) * SCALE), round((y - ORIGIN[1]) * SCALE)) for x, y in ring]
                q = [p for i, p in enumerate(q) if i == 0 or p != q[i - 1]]
                if len(q) >= 4:
                    packed.append(q)
            if not packed:
                continue
            size = 0 if area >= LARGE else 1 if area >= MEDIUM else 2
            varint(size, out)
            varint(len(packed), out)
            for q in packed:
                varint(len(q), out)
                px, py = 0, 0
                for x, y in q:
                    varint(x - px, out)
                    varint(y - py, out)
                    px, py = x, y
                points += len(q)
            parks += 1
            sizes[size] += 1

    meta = {"scale": SCALE, "origin": ORIGIN, "parks": parks}
    data = base64.b64encode(bytes(out)).decode()
    with open(dst, "w") as f:
        f.write("// Generated by scripts/build_parks.py. Do not edit by hand.\n")
        f.write("// Park data © OpenStreetMap contributors (ODbL), via Overture Maps Foundation.\n")
        f.write(f"export const PARK_META = {json.dumps(meta)};\n")
        f.write(f'export const PARK_DATA = "{data}";\n')
    print(f"{parks:,} green areas (large/medium/small: {sizes}), {points:,} points, {len(data)/1e6:.2f} MB as text")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3])
